"""add comment to transactions

Revision ID: 105b336296d6
Revises: df56785bc952
Create Date: 2023-08-19 17:07:32.724076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105b336296d6'
down_revision = 'df56785bc952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('comment', sa.String(length=200), nullable=True))

    # we need to make all positive transactions with comment 'topup'
    # and all negative transactions with comment 'expense'
    op.execute("UPDATE transactions SET comment = 'topup' WHERE amount_points > 0")
    op.execute("UPDATE transactions SET comment = 'expense' WHERE amount_points < 0")
    op.alter_column('transactions', 'comment', nullable=False)
    #     usd_amount: Mapped[Optional[float]] = mapped_column(DECIMAL(10, 2), nullable=True)
    op.add_column('transactions', sa.Column('usd_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'comment')
    # ### end Alembic commands ###
