"""add comment to transactions

Revision ID: 105b336296d6
Revises: df56785bc952
Create Date: 2023-08-19 17:07:32.724076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '105b336296d6'
down_revision = 'df56785bc952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('comment', sa.String(length=200), nullable=True))
    op.add_column('transactions', sa.Column('usd_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # we need to make all positive transactions with comment 'topup'
    # and all negative transactions with comment 'expense'
    op.execute("UPDATE transactions SET comment = 'topup', usd_amount = amount_points * 0.2 WHERE amount_points > 0")
    op.execute("UPDATE transactions SET comment = 'expense', usd_amount = amount_points * 0.2 WHERE amount_points < 0")
    op.alter_column('transactions', 'comment', nullable=False)
    op.drop_column('transactions', 'amount_points')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'comment')
    op.add_column('transactions', sa.Column('amount_points', sa.INTEGER(), autoincrement=False, nullable=True))
    connection = op.get_bind()
    connection.execute(
        text("UPDATE transactions SET amount_points = usd_amount * 5")
    )

    op.drop_column('transactions', 'usd_amount')
    # ### end Alembic commands ###
