"""initial migration

Revision ID: 1299e36be129
Revises: 
Create Date: 2023-07-09 13:05:31.322172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1299e36be129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.alter_column('products', 'photo_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('products', 'grade')
    op.drop_column('products', 'category')
    op.drop_column('products', 'genetic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('genetic', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('grade', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('products', 'photo_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
