"""initial check

Revision ID: 133b3c49a80a
Revises: e71ba0564901
Create Date: 2023-07-14 09:24:19.249978

"""

# revision identifiers, used by Alembic.
revision = '133b3c49a80a'
down_revision = 'e71ba0564901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
