"""optional to referrer

Revision ID: 14265c69ac25
Revises: 43a8bdd060ff
Create Date: 2023-09-08 09:22:41.170337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14265c69ac25'
down_revision = '43a8bdd060ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
