"""update for migration to usd from points

Revision ID: 45d859c77e83
Revises: 105b336296d6
Create Date: 2023-08-21 09:10:55.743822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d859c77e83'
down_revision = '105b336296d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('usd_amount', sa.Float(), nullable=False))
    op.drop_column('transactions', 'amount_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'usd_amount')
    # ### end Alembic commands ###
