"""add payment status

Revision ID: df56785bc952
Revises: 985a0c8b7893
Create Date: 2023-07-25 13:32:04.876597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df56785bc952"
down_revision = "985a0c8b7893"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "status", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.alter_column(
        "transactions", "order_id", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions", "order_id", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.drop_column("transactions", "status")
    # ### end Alembic commands ###
