"""initial check

Revision ID: f8094c788451
Revises: 133b3c49a80a
Create Date: 2023-07-14 09:25:07.162983

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8094c788451'
down_revision = '133b3c49a80a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('fk_tg_id', sa.Integer(), nullable=False),
                    sa.Column('urls', sa.Text(), nullable=False),
                    sa.Column('count_urls', sa.Integer(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['fk_tg_id'], ['users.tg_id'], ),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
